### PR TITLE
Update to work with current nim

### PR DESCRIPTION
**Pull request by stisa**
Updated to work with nim 0.14.2 and also generated documentation in /docs.
( With the changes in github pages you can public docs without a `gh-pages` branch )

### CODE REVIEW

**Comment by haldean** [comment]
Hey stisa! Thanks so much for the PR. I'm definitely interested in merging this; I haven't worked on it in a while but I definitely want to keep it working for people that use it. I only have a few questions/requests before merging: 
- is the reason you copied in zlib because newer Nim versions don't have built-in wrappers for it?
- can you put a link to where you got the source for `zlib.nim` in the source file?
- what's the license on `zlib.nim`? I want to make sure it's compatible with being included in a BSD-licensed project.

Thanks so much!

**Comment by haldean** [comment]
(also, once this is merged I'll change the setting on the repo to pull github pages from the `docs` branch)

**Comment by stisa** [comment]
Hi! Thanks for the quick reply. As for your questions:

Yes, the wrapper has been moved to [zip](https://github.com/nim-lang/zip) ( looking at the commit history, I think it happened in july 2015 ? )
The [zlib.nim](https://github.com/nim-lang/zip/blob/master/zip/zlib.nim) was taken from that library.
The license is a standard [MIT](https://github.com/nim-lang/zip/blob/master/LICENSE).
I included links to the file and the license as well as the text of the license at the top of `zlib.nim`, so it should be compliant now ( not sure, I'm rather new at licenses etc ).
Let me know if there's anything else you need!

Silvio

**Comment by haldean** [comment]
Great, this looks good. Thanks again for the PR!

**Comment by stisa** [comment]
Great, thanks! Would you mind adding this to [nimble](https://github.com/nim-lang/packages) ?
The entry could look something like this:

``` json
{ 
"name": "nimage", 
"tags": [ "png","graphic","encode","decode"], 
"method": "git", 
"license": "BSD3", 
"description": "Pure-Nim image encoding and decoding",
"web": "https://github.com/haldean/nimage", 
"url": "https://github.com/haldean/nimage" 
} 
```

**Pull request merged**
